"""
Django settings for HospitalHubServer project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-#8!r$x!m8!oxctt_x2fgy_j65@xgx!sf1+(89kw42c_92@-os'
=======
Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wv^sbd434msg)&z+jg+$11**g1n1695*+ozwfqg$xk8h)sk_x_'
>>>>>>> 97969be225cfb49aa6da4c5e428ba1c8b9fd53dd

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
<<<<<<< HEAD
ALLOWED_HOSTS = []
=======
ALLOWED_HOSTS = ['0.0.0.0']
>>>>>>> 97969be225cfb49aa6da4c5e428ba1c8b9fd53dd
=======
ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1']
>>>>>>> 3a6dc714066642d44e9ecf7fa1f23b462ed79b70


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MyHub',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HospitalHubServer.urls'
<<<<<<< HEAD

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
=======
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
>>>>>>> 97969be225cfb49aa6da4c5e428ba1c8b9fd53dd
=======
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
>>>>>>> 3a6dc714066642d44e9ecf7fa1f23b462ed79b70
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'

WSGI_APPLICATION = 'HospitalHubServer.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        #'User' :'dj',
        #'PASSWORDS' :'1231',
        
    }
=======
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'HospitalHub',
        'USER': 'dj',
        'PASSWORD': '1231',
    }
    
>>>>>>> 97969be225cfb49aa6da4c5e428ba1c8b9fd53dd
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
>>>>>>> 97969be225cfb49aa6da4c5e428ba1c8b9fd53dd

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
=======
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'
>>>>>>> 97969be225cfb49aa6da4c5e428ba1c8b9fd53dd

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.2/howto/static-files/
=======
# https://docs.djangoproject.com/en/3.1/howto/static-files/
>>>>>>> 97969be225cfb49aa6da4c5e428ba1c8b9fd53dd

STATIC_URL = '/static/'
