# Generated by Django 3.1.2 on 2020-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctoredu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Enter degree', max_length=200)),
                ('uni', models.CharField(help_text='Enter your Uni', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(help_text='Enter Hospital Description', max_length=10000)),
                ('building', models.CharField(blank=True, max_length=25, null=True)),
                ('street', models.CharField(blank=True, max_length=25, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True, unique=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('hospambid', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('edu', models.ManyToManyField(help_text='Select an education', to='myhub.doctoredu')),
                ('hospital', models.ManyToManyField(help_text='Select hospital(s):', to='myhub.hospital')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
