# Generated by Django 3.1.5 on 2021-01-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(default='default.jpg', upload_to='')),
                ('desc', models.CharField(default='No description available for this doctor.', help_text='Enter Doctor Description', max_length=10000)),
                ('speciality', models.CharField(default='No speciality available at this moment.', help_text='Enter Doctor Speciality', max_length=1000)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='doctoruni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your Uni', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(help_text='Enter Hospital Description', max_length=10000)),
                ('building', models.CharField(max_length=25, null=True)),
                ('street', models.CharField(max_length=25, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('profile', models.ImageField(default='default.jpg', upload_to='')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='default.jpg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.hospital')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.pincode'),
        ),
        migrations.CreateModel(
            name='doctoredu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Enter degree', max_length=200)),
                ('uni', models.ForeignKey(help_text='Select a uni for this degree', on_delete=django.db.models.deletion.CASCADE, to='myhub.doctoruni')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.doctor')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='edu',
            field=models.ManyToManyField(help_text='Select an education', to='myhub.doctoredu'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(help_text='Select hospital(s):', to='myhub.hospital'),
        ),
        migrations.CreateModel(
            name='hospphoneno',
            fields=[
                ('phonenumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('key1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.hospital')),
            ],
            options={
                'unique_together': {('key1', 'phonenumber')},
            },
        ),
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('key2', models.IntegerField(primary_key=True, serialize=False)),
                ('ambvehicletype', models.CharField(blank=True, max_length=25, null=True)),
                ('vehiclecapacity', models.IntegerField(blank=True, null=True)),
                ('key1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.hospital')),
            ],
            options={
                'unique_together': {('key1', 'key2')},
            },
        ),
    ]
