# Generated by Django 3.1.5 on 2021-01-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambvehiclecapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambvehicletype', models.CharField(blank=True, max_length=25, null=True)),
                ('vehiclecapacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='vehiclecapacity',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='ambvehicletype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myhub.ambvehiclecapacity'),
            preserve_default=False,
        ),
    ]
