# Generated by Django 3.1.3 on 2020-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0002_auto_20201031_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='/home/akashmishra1128/MiniProject/HospitalHub/default.png', upload_to=''),
        ),
    ]
