# Generated by Django 3.1.3 on 2020-11-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0003_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='/home/akashmishra1128/MiniProject/HospitalHub/media/default.png', upload_to=''),
        ),
    ]
