# Generated by Django 3.1.3 on 2020-11-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0006_auto_20201111_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(upload_to=''),
        ),
    ]
