# Generated by Django 3.1.3 on 2020-11-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0007_auto_20201111_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=''),
        ),
    ]
