# Generated by Django 3.1.3 on 2020-11-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0009_auto_20201112_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, default='photo.jpg', null=True, upload_to=''),
        ),
    ]
