# Generated by Django 3.1.3 on 2020-11-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0012_auto_20201120_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('key2', models.IntegerField(primary_key=True, serialize=False)),
                ('ambvehicletype', models.CharField(blank=True, max_length=25, null=True)),
                ('vehiclecapacity', models.IntegerField(blank=True, null=True)),
                ('key1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.doctor')),
            ],
            options={
                'unique_together': {('key1', 'key2')},
            },
        ),
    ]
