# Generated by Django 3.1.3 on 2020-11-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0015_auto_20201121_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='key1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.hospital'),
        ),
    ]
