# Generated by Django 3.1.3 on 2020-11-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0016_auto_20201121_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospphoneno',
            fields=[
                ('phonenumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('key1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.hospital')),
            ],
            options={
                'unique_together': {('key1', 'phonenumber')},
            },
        ),
    ]
