# Generated by Django 3.1.2 on 2020-11-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0017_hospphoneno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='doctor_review',
        ),
        migrations.AddField(
            model_name='hospital',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='hospital_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhub.hospital')),
            ],
        ),
    ]
