# Generated by Django 3.1.2 on 2020-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0018_auto_20201122_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hospambid',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
