# Generated by Django 3.1.2 on 2020-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0019_auto_20201123_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
