# Generated by Django 3.1.2 on 2020-11-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0020_auto_20201123_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctoruni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your Uni', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='doctoredu',
            name='uni',
            field=models.ForeignKey(help_text='Select a uni for this degree', on_delete=django.db.models.deletion.CASCADE, to='myhub.doctoruni'),
        ),
    ]
