# Generated by Django 3.1.2 on 2020-11-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0021_auto_20201123_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruni',
            name='name',
            field=models.CharField(help_text='Enter your Uni', max_length=200, unique=True),
        ),
    ]
