# Generated by Django 3.1.3 on 2020-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0026_auto_20201123_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
