# Generated by Django 3.1.2 on 2020-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0027_auto_20201123_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
